FROM node:22.9.0-alpine
LABEL authors="Maria Hidalgo"

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY ../react-ui/package.json ./
COPY ../react-ui/package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY ../react-ui/ ./

# start app
CMD ["npm", "start"]
